
jQuery(document).ready(function(){jQuery('#cl_settings').find('input[type=radio]').bind('click',function(){cl_submitSettings();});jQuery('#cl_subscribe_subscribe').bind('click',function(event){if(event)
event.preventDefault();if(cl_validateEmail(jQuery('#cl_subscribe_email').val())){jQuery.getJSON('http://www.contentlook.co/api/?callback=?',{action:'register',email:jQuery('#cl_subscribe_email').val(),url:jQuery('#cl_subscribe_url').val(),sendemail:jQuery('#cl_settings').find('input[name=cl_sendemail]:checked').val(),},function(data){if(typeof data.token!=='undefined'&&typeof data.signup!=='undefined'){jQuery.getJSON(cl_Query.ajaxurl,{action:'cl_settings_connected',token:data.token,nonce:cl_Query.nonce});jQuery('#cl_token').val(data.token);jQuery('#cl_option_connect_error').hide();setTimeout(function(){cl_checkAudit();},100);}else{jQuery('#cl_option_connect_error').html('Could not connect to server!').show();}});}else{alert('The email is not valid! Please enter a valid email address. Thank you');}});if(jQuery('#cl_token').val()!='')
cl_checkAudit()});function cl_checkAudit(){jQuery.getJSON('http://www.contentlook.co/api/?callback=?',{action:'check_audit',token:jQuery('#cl_token').val(),},function(data){if(typeof data.audit!=='undefined'&&typeof data.error!=='undefined'){if(data.audit==true&&data.error==false){jQuery('#cl_option_audit_link').find('a').attr('href','http://www.contentlook.co/user/audit/'+jQuery('#cl_token').val());jQuery('#cl_option_audit_link').show();if(typeof data.datetime!=='undefined'&&jQuery('cl_audit_date').length==0){jQuery('#cl_option_audit_link').after('<span id="cl_audit_date">Last update: '+data.datetime+'</span>');}
jQuery('#cl_option_connect_frame').hide();jQuery('#cl_option_audit_notready').hide();jQuery('#cl_option_audit_error').hide();}else
if(data.audit==true&&data.error==true){jQuery('#cl_option_connect_frame').hide();jQuery('#cl_option_audit_notready').hide();jQuery('#cl_option_audit_error').show();}else{jQuery('#cl_option_connect_frame').hide();jQuery('#cl_option_audit_notready').show();jQuery('#cl_option_audit_error').hide();setTimeout(function(){cl_checkAudit();},5000);}
jQuery('#cl_option_audit').show();}else{jQuery('#cl_option_audit_link').html('Could not connect to server!').show();}});}
function cl_validateEmail($email){if($email=='')
return false;var emailReg=/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;if(!emailReg.test($email)){return false;}else{return true;}}
function cl_submitSettings(){jQuery.getJSON(cl_Query.ajaxurl,{action:'cl_settings_update',data:jQuery('#cl_settings').find('form').serialize(),nonce:cl_Query.nonce});}